import Head from 'next/head';
import MobileContainer from './../components/mobile/MobileContainer';
import classes from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome to Lance Gee Page</title>
        <meta
          name="Lance Gee Personal Page"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileContainer />
    </div>
  );
}
